### ISSUE TITLE
Required PHP Version: 5.5.x

### ISSUE THREAD

**Issue by Puzo** [opensolutions/doctrine2bridge-l5#1]
Is there any chance to run this on PHP 5.4.x version?

**Comment by barryo** [comment]
It would _probably_ run just fine on PHP 5.4.

**Comment by Puzo** [comment]
Not sure, I am getting this error:

 Problem 1
    - opensolutions/doctrine2bridge-l5 v2.4.2 requires php >=5.5.0 -> no matching package found.
    - opensolutions/doctrine2bridge-l5 v2.4.1 requires php >=5.5.0 -> no matching package found.
    - opensolutions/doctrine2bridge-l5 v2.4.0 requires php >=5.5.0 -> no matching package found.
    - Installation request for opensolutions/doctrine2bridge-l5 2.4.\* -> satisfiable by opensolutions/doctrine2bridge-l5[v2.4.0, v2.4.1, v2.4.2].

**Comment by barryo** [comment]
Yeah, just took a look at the code and it uses some 5.5 features such as: Class name resolution via `::class`.

So, I'm afraid 5.5 is a requirement. 

Should be easy for fork, change composer.json to require 5.4 and weed out the 5.5 specific parts.
